male(gf).
male(di).
male(jianbo).
female(gm).
female(xin).
female(yuan).
female(yuqing).
father(gf,jianbo).
father(jianbo,di).
father(di,yuqing).
mother(gm,jianbo).
mother(xin,di).
mother(yuan,yuqing).
grandfather(X,Y):-father(X,Z),father(Z,Y).
grandmother(X,Y):-mother(X,Z),father(Z,Y).
parent(X,Y):-mother(X,Y).
parent(X,Y):-father(X,Y).
ancestor(X,Y):-parent(X,Y).
ancestor(X,Y):-parent(X,Z),ancestor(Z,Y).
daughter(Y,X):-father(X,Y),female(Y).